#!/usr/bin/env bash
# Script that displays information about subdomains.

display () {
	local domain="$1"
	local subdomain="$2"

	if [ -z "$subdomain" ];
	then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}";
	do
		record_type="A"
		destination=$(dig +short -t A "$sub.$domain" | tail -n1)

		echo "The subdomain $sub is a $record_type record and points to $destination"
	done
}

domain="$1"
subdomain="$2"

display "$domain" "$subdomain"
