#!/usr/bin/env bash
# Script configures Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx

bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
REDIRECT="https://github.com/Hovixen/"

echo "server {
	listen 80;
	server_name _;
	location / {
	return 301 $REDIRECT;
	}
}" > /etc/nginx/sites-available/default
service nginx start
