#!/usr/bin/env bash
# Script configures Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx

bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
REDIRECT="https://github.com/Hovixen/"

ERR_MSG="Ceci n'est pas une page"

echo "server {
	listen 80;
	server_name _;
	location = /redirect_me {
		return 301 $REDIRECT;
	}

	error_page 404 /404_error;
	location = /404_error {
		internal;
		return 404 \"$ERR_MSG\n\";
	}
}" > /etc/nginx/sites-available/default
service nginx restart
