#!/usr/bin/python3
""" recursive function that queries the Reddit API, parses the title
of all hot articles and prints a sorted count of given keyword
(case insensitive, delimited by space)
"""
import requests


def count_words(subreddit, word_list
