#!/usr/bin/env bash
# Script that sets the port 80 with minimum number of commands
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
