#!/usr/bin/env bash
# Script that sets the port 80
CONFIG="
	server {
		listen 80;
		server_name _;
		
		location / {
		root /var/www/html;
		index index.html;
		}
	}"
echo "$CONFIG" > /etc/nginx/sites-enabled/default
service nginx restart
