#!/usr/bin/env bash
#Bash script that displays messages when read some signals

function delete_and_exit()
{
	rm -rf /var/run/myscript.pid
	exit 0
}

function signal_termination()
{
	echo "I hate the kill command"
	delete_and_exit
}

function signal_interrupt
{
	echo "Y U no love me?!"
}

function quit()
{
	delete_and_exit
}

function message()
{
	while :
	do
		echo "To infinity and beyond"
		sleep 2
	done
}

trap signal_termination SIGTERM
trap signal_interrupt SIGINT
trap signal_quit SIGQUIT

echo $$ > /var/run/myscript.pid
message
