#!/usr/bin/env bash
# script configures an unbuntu server

cp /etc/hosts ~/host.bak
sed -i 's/127.0.0.1/127.0.0.2/' ~/host.bak
sed -i '/2i8.8.8.8 facebook.com'/ ~/host.bak

cp -f ~/host.bak /etc/hosts
